main: com.edtheloon.MineCar.MCMain
name: MineCar
author: EdTheLoon
website:
collaborators: Lathanael & Lemonzap
description: Turn a minecart into a MineCar!
version: 0.3
soft-depend: [Spout]

commands:
    minecar:
        description: Create or remove a MineCar
        usage: |
            /<command> remove <player> - Removes <player>'s MineCar
            /<command> remove all - Removes all MineCars
            /<command> reload - Reloads the configuration
permissions:
    MineCar.user:
        description: Allows creation and controlling of a MineCar
        default: false
        children:
            MineCar.create: true
            MineCar.control: true
    MineCar.*:
        description: Gives access to all MineCar features
        default: false
        children:
            MineCar.create: true
            MineCar.control: true
            MineCar.remove: true
    MineCar.create:
        description: Allows the creation of a MineCar
        default: false
    MineCar.control:
        description: Allows the controlling of a MineCar
        default: false
    MineCar.remove:
        description: Allows the removal of a MineCar
        default: op
    MineCar.reload:
        description: Allows reloading the MineCar configuration
        default: op