main: com.edtheloon.MineCar.Minecar
name: MineCar
author: EdTheLoon
description: Turn a minecart into a car!
version: 0.1
soft-depend: Spout

commands:
    minecar:
        description: Create or remove a MineCar
        usage: |
            /minecar create - Creates a MineCar
            /minecar remove - Removes a MineCar
permissions:
    MineCar.create:
        description: Allows the creation of a MineCar
        default: false
    MineCar.remove:
        description: Allows the removal of a MineCar
        default: false
    MineCar.admin:
        description: Allows the removal of any player's MineCar and other admin features
        default: op